# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=1.21.1
loader_version=0.18.2
# Mod Properties
mod_version=2.5
maven_group=com.lowdragmc.ldlib2
archives_base_name=LDLib2
mod_id=ldlib2
mod_name=LDLib2
mod_description=LowDragLib2
mod_url=https://github.com/lowdragmc/LDLib
mod_license=MIT
# Kotlin
kotlin_stdlib_version=2.1.20
# Yoga layout engine
yoga_version=1.0.0
# Taffy
taffy_version=1.1.4
# moddevmcp
moddevmcp_version=0.3
fabric_version=0.116.9+1.21.1